=== BrittonFischer/BrittonFischer.github.io/CSE445/Cruises.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Cruises">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Cruise" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="ParentCompany" type="xs:string" />
							<xs:element name="Name" type="xs:string" />
							<xs:element name="Reservation">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Phone" type="xs:string" />
										<xs:element name="Url" type="xs:string" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Headquarter" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="City" type="xs:string" />
										<xs:element name="State" type="xs:string" />
									</xs:sequence>
									<xs:attribute name="Zip" type="xs:string" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element name="DeparturePorts">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Port" type="xs:string" minOccurs="2"
											maxOccurs="unbounded" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="FoundedIn" type="xs:string" use="optional" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== BrittonFischer/BrittonFischer.github.io/CSE445/Cruises.xml
<Cruises xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="Cruises.xsd">
	<Cruise FoundedIn="1972">
		<ParentCompany>Carnival Corporation</ParentCompany>
		<Name>Carnival Conquest</Name>
		<Reservation>
			<Phone>1-800-CARNIVAL</Phone>
			<Url>www.carnival.com</Url>
		</Reservation>
		<Headquarter Zip="33178">
			<City>Miami</City>
			<State>Florida</State>
		</Headquarter>
		<DeparturePorts>
			<Port>Miami</Port>
			<Port>Nassau</Port>
		</DeparturePorts>
	</Cruise>
	<Cruise>
		<ParentCompany>Carnival Corporation</ParentCompany>
		<Name>Carnival Conquest</Name>
		<Reservation>
			<Phone>1-800-CARNIVAL</Phone>
			<Url>www.carnival.com</Url>
		</Reservation>
		<Headquarter Zip="33178">
			<City>Miami</City>
			<State>Florida</State>
		</Headquarter>
		<DeparturePorts>
			<Port>Miami</Port>
			<Port>Half Moon Cay</Port>
			<Port>Nassau</Port>
		</DeparturePorts>
	</Cruise>
	<Cruise>
		<ParentCompany>Carnival Corporation</ParentCompany>
		<Name>Carnival Conquest</Name>
		<Reservation>
			<Phone>1-800-CARNIVAL</Phone>
			<Url>www.carnival.com</Url>
		</Reservation>
		<Headquarter Zip="33178">
			<City>Miami</City>
			<State>Florida</State>
		</Headquarter>
		<DeparturePorts>
			<Port>Miami</Port>
			<Port>Nassau</Port>
			<Port>Half Moon Cay</Port>
		</DeparturePorts>
	</Cruise>
	<Cruise>
		<ParentCompany>Carnival Corporation</ParentCompany>
		<Name>Carnival Conquest</Name>
		<Reservation>
			<Phone>1-800-CARNIVAL</Phone>
			<Url>www.carnival.com</Url>
		</Reservation>
		<Headquarter Zip="33178">
			<City>Miami</City>
			<State>Florida</State>
		</Headquarter>
		<DeparturePorts>
			<Port>Miami</Port>
			<Port>Princess Cays</Port>
			<Port>Nassau</Port>
		</DeparturePorts>
	</Cruise>
	<Cruise>
		<ParentCompany>Carnival Corporation</ParentCompany>
		<Name>Carnival Glory</Name>
		<Reservation>
			<Phone>1-800-CARNIVAL</Phone>
			<Url>www.carnival.com</Url>
		</Reservation>
		<Headquarter Zip="32920">
			<City>Port Canaveral</City>
			<State>Florida</State>
		</Headquarter>
		<DeparturePorts>
			<Port>Port Canaveral</Port>
			<Port>Bimini</Port>
		</DeparturePorts>
	</Cruise>
	<Cruise>
		<ParentCompany>Carnival Corporation</ParentCompany>
		<Name>Carnival Radiance</Name>
		<Reservation>
			<Phone>1-800-CARNIVAL</Phone>
			<Url>www.carnival.com</Url>
		</Reservation>
		<Headquarter Zip="90802">
			<City>Los Angeles</City>
			<State>California</State>
		</Headquarter>
		<DeparturePorts>
			<Port>Los Angeles</Port>
			<Port>Catalina Island</Port>
			<Port>Ensenada</Port>
		</DeparturePorts>
	</Cruise>
	<Cruise>
		<ParentCompany>Carnival Corporation</ParentCompany>
		<Name>Carnival Conquest</Name>
		<Reservation>
			<Phone>1-800-CARNIVAL</Phone>
			<Url>www.carnival.com</Url>
		</Reservation>
		<Headquarter Zip="33178">
			<City>Miami</City>
			<State>Florida</State>
		</Headquarter>
		<DeparturePorts>
			<Port>Miami</Port>
			<Port>Princess Cays</Port>
			<Port>Nassau</Port>
		</DeparturePorts>
	</Cruise>
	<Cruise>
		<ParentCompany>Carnival Corporation</ParentCompany>
		<Name>Carnival Conquest</Name>
		<Reservation>
			<Phone>1-800-CARNIVAL</Phone>
			<Url>www.carnival.com</Url>
		</Reservation>
		<Headquarter Zip="33178">
			<City>Miami</City>
			<State>Florida</State>
		</Headquarter>
		<DeparturePorts>
			<Port>Miami</Port>
			<Port>Princess Cays</Port>
			<Port>Nassau</Port>
		</DeparturePorts>
	</Cruise>
	<Cruise>
		<ParentCompany>Carnival Corporation</ParentCompany>
		<Name>Carnival Glory</Name>
		<Reservation>
			<Phone>1-800-CARNIVAL</Phone>
			<Url>www.carnival.com</Url>
		</Reservation>
		<Headquarter Zip="32920">
			<City>Port Canaveral</City>
			<State>Florida</State>
		</Headquarter>
		<DeparturePorts>
			<Port>Port Canaveral</Port>
			<Port>Nassau</Port>
			<Port>Princess Cays</Port>
		</DeparturePorts>
	</Cruise>
	<Cruise>
		<ParentCompany>Carnival Corporation</ParentCompany>
		<Name>Carnival Radiance</Name>
		<Reservation>
			<Phone>1-800-CARNIVAL</Phone>
			<Url>www.carnival.com</Url>
		</Reservation>
		<Headquarter Zip="90802">
			<City>Los Angeles</City>
			<State>California</State>
		</Headquarter>
		<DeparturePorts>
			<Port>Los Angeles</Port>
			<Port>Ensenada</Port>
		</DeparturePorts>
	</Cruise>
</Cruises>
